# Site settings
title: hulot
tag_text: A React component and test generator
description: Because doing things by hand is boring.
url: "http://hulot.codemode.rocks"

# Build settings
markdown: kramdown

exclude: ["README.md"]
